services:
  - type: web
    name: vdb-map-bangladesh
    env: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
